.SUFFIXES:
.SUFFIXES: .c .o .P

GENOBJS = tb8gen.o movegen.o index.o generate.o merge.o kslice.o probe.o \
	  stats.o join.o permute.o permute462.o permute10.o compress.o rans.o \
	  huffman.o util.o threads.o checksum.o hash.o

VEROBJS = tb8ver.o movegen.o index.o verify.o kslice.o probe.o decompress.o \
	  rans.o huffman.o util.o threads.o hash.o

GENPOBJS = tb8genp.o movegen.o index.o generatep.o mergep.o kslicep.o \
	   probe.o stats.o joinp.o permutepk.o permutep.o compress.o rans.o \
	   huffman.o util.o threads.o checksum.o hash.o

OBJS = $(sort $(GENOBJS) $(VEROBJS))
POBJS = $(sort $(GENPOBJS))

include $(OBJS:%.o=$(BUILD)/%.dep)
include $(POBJS:%.o=$(PBUILD)/%.dep)

$(BUILD)/%.o: %.c $(BUILD)/%.dep
	@mkdir -p $(BUILD)
	$(CC) $(CFLAGS) -c $*.c $(FLAGS) -o $(BUILD)/$*.o

$(BUILD)/%.dep: %.c
	@mkdir -p $(BUILD)
	$(CC) -MM $(CFLAGS) $(FLAGS) $*.c -MT $(BUILD)/$*.o -MT $(BUILD)/$*.dep -MF $(BUILD)/$*.dep

$(PBUILD)/%.o: %.c $(PBUILD)/%.dep
	@mkdir -p $(PBUILD)
	$(CC) $(CFLAGS) -DHAS_PAWNS -c $*.c $(FLAGS) -o $(PBUILD)/$*.o

$(PBUILD)/%.dep: %.c
	@mkdir -p $(PBUILD)
	$(CC) -MM $(CFLAGS) -DHAS_PAWNS $(FLAGS) $*.c -MT $(PBUILD)/$*.o -MT $(PBUILD)/$*.dep -MF $(PBUILD)/$*.dep

$(CLEAN):
	rm -f $(BUILD)/*.o

$(CLEANP):
	rm -f $(PBUILD)/*.o

$(TBGEN): $(GENOBJS:%=$(BUILD)/%)
	$(CC) $(CFLAGS) -o $(TBGEN) $(GENOBJS:%=$(BUILD)/%) $(LDFLAGS)

$(TBVER): $(VEROBJS:%=$(BUILD)/%)
	$(CC) $(CFLAGS) -o $(TBVER) $(VEROBJS:%=$(BUILD)/%) $(LDFLAGS)

$(TBGENP): $(GENPOBJS:%=$(PBUILD)/%)
	$(CC) $(CFLAGS) -o $(TBGENP) $(GENPOBJS:%=$(PBUILD)/%) $(LDFLAGS)
